using System.ComponentModel;

namespace EronNew.Resources
{
    public enum LocalizedPhrases
    {

        [Description("<strong>All</strong> Languages Available")] AllLanguagesAvailable,
        [Description("<strong>Boosted</strong> Advertisement")] BoostedAdvertisement,
        [Description("Account Management")] AccountManagement,
        [Description("Activation")] Activation,
        [Description("Activation of Premium Ad")] ActivationofPremiumAd,
        [Description("Active")] Active,
        [Description("Ad Code")] AdCode,
        [Description("Ad Management")] AdManagement,
        [Description("Ad Type")] AdType,
        [Description("Additional characteristics")] Additionalcharacteristics,
        [Description("Additional information")] Additionalinformation,
        [Description("Additional Property Features")] AdditionalPropertyFeatures,
        [Description("Address")] Address,
        [Description("Air Condition")] AirCondition,
        [Description("and")] and,
        [Description("Apartment")] Apartment,
        [Description("Apartment Complex")] ApartmentComplex,
        [Description("Area")] Area,
        [Description("Ask for the Price")] AskforthePrice,
        [Description("Balance")] Balance,
        [Description("Bathrooms")] Bathrooms,
        [Description("BBQ")] BBQ,
        [Description("Bedrooms")] Bedrooms,
        [Description("Broker Fee")] BrokerFee,
        [Description("Building")] Building,
        [Description("Bungalow")] Bungalow,
        [Description("Business building")] Businessbuilding,
        [Description("By clicking <em> Register </em> you automatically agree to our")] ByclickingRegisteryouautomaticallyagreetoour,
        [Description("By Completing the submission of your first Ad will be credited")] ByCompletingthesubmissionofyourfirstAdwillbecredited,
        [Description("Cancel")] Cancel,
        [Description("Category")] Category,
        [Description("Change email")] Changeemail,
        [Description("Change Password")] ChangePassword,
        [Description("Choose")] Choose,
        [Description("Choose a profile image")] Chooseaprofileimage,
        [Description("Choose tags for the description")] Choosetagsforthedescription,
        [Description("Choose which package you want for your ad.")] Choosewhichpackageyouwantforyourad,
        [Description("Choose your preferred language")] Chooseyourpreferredlanguage,
        [Description("Click here to Logout")] ClickheretoLogout,
        [Description("CloakRoom")] CloakRoom,
        [Description("Close")] Close,
        [Description("Commands")] Commands,
        [Description("Commercial")] Commercial,
        [Description("Company")] Company,
        [Description("Complete")] Complete,
        [Description("Complete Registration")] CompleteRegistration,
        [Description("Completed")] Completed,
        [Description("Conference Room")] ConferenceRoom,
        [Description("Confirm Password")] ConfirmPassword,
        [Description("Construction")] Construction,
        [Description("Construction Year")] ConstructionYear,
        [Description("Contact")] Contact,
        [Description("Contact Info")] ContactInfo,
        [Description("Contact Phone")] ContactPhone,
        [Description("Contact us")] Contactus,
        [Description("Control Panel")] ControlPanel,
        [Description("Cottage")] Cottage,
        [Description("County/Region")] CountyRegion,
        [Description("Craft Property")] CraftProperty,
        [Description("Create Draft Ad")] CreateDraftAd,
        [Description("Create your own mobile presentation (Compatible with iPhone and iPad)")] CreateyourownmobilepresentationCompatiblewithiPhoneandiPad,
        [Description("Current Balance")] CurrentBalance,
        [Description("Current Costs")] CurrentCosts,
        [Description("Delete")] Delete,
        [Description("Deleted")] Deleted,
        [Description("Demand")] Demand,
        [Description("Description")] Description,
        [Description("Desired Information from Buyers")] DesiredInformationfromBuyers,
        [Description("Detached House")] DetachedHouse,
        [Description("Do you need help")] Doyouneedhelp,
        [Description("Draft")] Draft,
        [Description("Drag the photos here")] Dragthephotoshere,
        [Description("Edit")] Edit,
        [Description("Elevator")] Elevator,
        [Description("Email")] Email,
        [Description("euroSymbol")] euroSymbol,
        [Description("Exchange Rate Table")] ExchangeRateTable,
        [Description("Exhibition Area")] ExhibitionArea,
        [Description("Farm/Ranch")] FarmRanch,
        [Description("Fill in the email to have the password reset email sent to you.")] Fillintheemailtohavethepasswordresetemailsenttoyou,
        [Description("Finance")] Finance,
        [Description("Fireplace")] Fireplace,
        [Description("floor")] floor,
        [Description("Follow us")] Followus,
        [Description("Forgot your password")] Forgotyourpassword,
        [Description("from")] from,
        [Description("Furniture")] Furniture,
        [Description("Garden")] Garden,
        [Description("greater than 100")] greaterthan100,
        [Description("Gym")] Gym,
        [Description("Hall")] Hall,
        [Description("Heating System")] HeatingSystem,
        [Description("Hidden Searches")] HiddenSearches,
        [Description("Hide")] Hide,
        [Description("Highest -> Lowest Price")] HighestLowestPrice,
        [Description("Home Energy Rate")] HomeEnergyRate,
        [Description("Hotel")] Hotel,
        [Description("Houseboat")] Houseboat,
        [Description("Housekeeping")] Housekeeping,
        [Description("How can we help you")] Howcanwehelpyou,
        [Description("How Many Bathrooms Does It Have?")] HowManyBathroomsDoesItHave,
        [Description("How Many Bedrooms Does It Have?")] HowManyBedroomsDoesItHave,
        [Description("Id")] Id,
        [Description("Important Information")] ImportantInformation,
        [Description("Inactive")] Inactive,
        [Description("Industrial Property")] IndustrialProperty,
        [Description("Info Card")] InfoCard,
        [Description("Internet Fiber")] InternetFiber,
        [Description("Investment")] Investment,
        [Description("Join to our Page")] JointoourPage,
        [Description("Land")] Land,
        [Description("Languages")] Languages,
        [Description("Living room")] Livingroom,
        [Description("Locked")] Locked,
        [Description("Loft")] Loft,
        [Description("Login")] Login,
        [Description("Login/Register")] LoginRegister,
        [Description("Logout")] Logout,
        [Description("Lowest To Highest")] LowestToHighest,
        [Description("Maisonette")] Maisonette,
        [Description("Mandatory Information")] MandatoryInformation,
        [Description("Master")] Master,
        [Description("maximum of Characters are 5")] maximumofCharactersare5,
        [Description("minimum Three Characters")] minimumThreeCharacters,
        [Description("Mobile")] Mobile,
        [Description("Mobile Home")] MobileHome,
        [Description("Month")] Month,
        [Description("Months")] Months,
        [Description("Most Popular")] MostPopular,
        [Description("Municipality / District")] MunicipalityDistrict,
        [Description("My Card")] MyCard,
        [Description("My Favorites")] MyFavorites,
        [Description("My information")] Myinformation,
        [Description("My Notes")] MyNotes,
        [Description("My Orders")] MyOrders,
        [Description("Name")] Name,
        [Description("New Construction")] NewConstruction,
        [Description("No")] No,
        [Description("No ads were found according to Search filters.")] NoadswerefoundaccordingtoSearchfilters,
        [Description("No Orders To Display")] NoOrdersToDisplay,
        [Description("Notes")] Notes,
        [Description("number")] number,
        [Description("Obligatory")] Obligatory,
        [Description("Offer")] Offer,
        [Description("Office")] Office,
        [Description("Ok")] Ok,
        [Description("Once the download is complete. Copy the link here")] OncethedownloadiscompleteCopythelinkhere,
        [Description("only Number")] onlyNumber,
        [Description("optional")] optional,
        [Description("Orders History")] OrdersHistory,
        [Description("Other Categories")] OtherCategories,
        [Description("Other Properties")] OtherProperties,
        [Description("Our Services")] OurServices,
        [Description("Parcels")] Parcels,
        [Description("Parking")] Parking,
        [Description("Parking Area")] ParkingArea,
        [Description("Password")] Password,
        [Description("Penthouse")] Penthouse,
        [Description("Personal settings")] Personalsettings,
        [Description("Pets")] Pets,
        [Description("Photos")] Photos,
        [Description("Place your ad")] Placeyourad,
        [Description("Please enter an email address for this site below and click the Register button to finish logging in.")] PleaseenteranemailaddressforthissitebelowandclicktheRegisterbuttontofinishloggingin,
        [Description("Plot of Land")] PlotofLand,
        [Description("Pool")] Pool,
        [Description("Post a request")] Postarequest,
        [Description("PostalCode")] PostalCode,
        [Description("Prefabricated Home")] PrefabricatedHome,
        [Description("Premium")] Premium,
        [Description("Premium Features")] PremiumFeatures,
        [Description("Prepaid Balance for Ads")] PrepaidBalanceforAds,
        [Description("Preview")] Preview,
        [Description("Preview <strong>360<sup>o</sup></strong>")] Preview360o,
        [Description("Preview 360")] Preview360,
        [Description("Price")] Price,
        [Description("Print")] Print,
        [Description("Property Area")] PropertyArea,
        [Description("Property Category")] PropertyCategory,
        [Description("Property Features")] PropertyFeatures,
        [Description("Property Price")] PropertyPrice,
        [Description("Property Type")] PropertyType,
        [Description("Public")] Public,
        [Description("Publish")] Publish,
        [Description("Publish Ad")] PublishAd,
        [Description("Publish/Save")] PublishSave,
        [Description("Range Price")] RangePrice,
        [Description("Rating")] Rating,
        [Description("Recent Posts")] RecentPosts,
        [Description("Recent Searches")] RecentSearches,
        [Description("Refill Balance")] RefillBalance,
        [Description("Register")] Register,
        [Description("Register from the applications")] Registerfromtheapplications,
        [Description("Rent")] Rent,
        [Description("Resend")] Resend,
        [Description("Residential")] Residential,
        [Description("Retry")] Retry,
        [Description("Safety door")] Safetydoor,
        [Description("Safety Frames")] SafetyFrames,
        [Description("Sale")] Sale,
        [Description("Save")] Save,
        [Description("Save Search")] SaveSearch,
        [Description("Saved Searches")] SavedSearches,
        [Description("Search")] Search,
        [Description("Search Filters")] SearchFilters,
        [Description("Security Alarm")] SecurityAlarm,
        [Description("See Other Seller Ads")] SeeOtherSellerAds,
        [Description("Select")] Select,
        [Description("Select the energy rate of the Property (if available)")] SelecttheenergyrateofthePropertyifavailable,
        [Description("Semi-outdoors")] Semioutdoors,
        [Description("Send")] Send,
        [Description("Send verification email")] Sendverificationemail,
        [Description("Send your comments <strong>here</strong>.")] Sendyourcommentshere,
        [Description("Send your message")] Sendyourmessage,
        [Description("Shall we check ?")] Shallwecheck,
        [Description("Share")] Share,
        [Description("Share on Facebook")] ShareonFacebook,
        [Description("Shop")] Shop,
        [Description("Show")] Show,
        [Description("Specifications of image")] Specificationsofimage,
        [Description("Square")] Square,
        [Description("Status Ad")] StatusAd,
        [Description("Storage")] Storage,
        [Description("Studio")] Studio,
        [Description("Subcategory")] Subcategory,
        [Description("Subject")] Subject,
        [Description("Submit")] Submit,
        [Description("Submit Post")] SubmitPost,
        [Description("Subscribe to our newsletter")] Subscribetoournewsletter,
        [Description("Subtitle")] Subtitle,
        [Description("Surname")] Surname,
        [Description("Terms of use")] Termsofuse,
        [Description("Thank you")] Thankyou,
        [Description("The Welcome Voucher has just been activated")] TheWelcomeVoucherhasjustbeenactivated,
        [Description("Title/Name")] TitleName,
        [Description("to")] to,
        [Description("Type")] Type,
        [Description("Type your message here")] Typeyourmessagehere,
        [Description("Unlocked")] Unlocked,
        [Description("Uploading photos started")] Uploadingphotosstarted,
        [Description("Usage For The Current Month")] UsageForTheCurrentMonth,
        [Description("valid City")] validCity,
        [Description("View")] View,
        [Description("views")] views,
        [Description("Wallet")] Wallet,
        [Description("WC")] WC,
        [Description("WebSite")] WebSite,
        [Description("Welcome to Eron.gr")] WelcometoErongr,
        [Description("WishList")] WishList,
        [Description("Write a short description")] Writeashortdescription,
        [Description("Write To Us")] WriteToUs,
        [Description("Year of Renovation")] YearofRenovation,
        [Description("Yes")] Yes,
        [Description("You can also connect from the applications")] Youcanalsoconnectfromtheapplications,
        [Description("You can choose what amenities are available for the property")] Youcanchoosewhatamenitiesareavailablefortheproperty,
        [Description("You can create your own Preview 360 video <sup>o</sup> with Matterport Capture")] YoucancreateyourownPreview360videoowithMatterportCapture,
        [Description("You can reset your password now.")] Youcanresetyourpasswordnow,
        [Description("You do not have access to this resource.")] Youdonothaveaccesstothisresource,
        [Description("You have successfully logged out of the application.")] Youhavesuccessfullyloggedoutoftheapplication,
        [Description("You upload the presentation to your account")] Youuploadthepresentationtoyouraccount,
        [Description("You've successfully authenticated with")] Youvesuccessfullyauthenticatedwith,




        // Translated

        //[Description("")],
        //[Description("")],
        //[Description("")],
        //[Description("")],
        //[Description("")],
        //[Description("")],
        //[Description("")],
        //[Description("")],
        //[Description("")],


        [Description("<strong>Boosted</strong> Advertisement")] HtmlBoostedAdvertisment,
        [Description("Preview <strong>360<sup>o</sup></strong>")] HtmlPreview360,
        [Description("<strong>All</strong> Languages Available")] HtmlAllLanguagesAvailable,
        [Description("Activation of Premium Ad")] ActivationMessage1,
        [Description("Choose which package you want for your ad.")] ActivationMessage2,
        [Description("You can create your own Preview 360 video <sup>o</sup> with Matterport Capture")] Matter1,
        [Description("Create your own mobile presentation (Compatible with iPhone and iPad)")] Matter2,
        [Description("You upload the presentation to your account")] Matter3,
        [Description("Once the download is complete. Copy the link here")] Matter4,
        [Description("Welcome to Eron.gr")] WelcomeMessage0,
        [Description("The Welcome Voucher has just been activated")] WelcomeVoucherMessage1,
        [Description("By Completing the submission of your first Ad will be credited")] WelcomeVoucherMessage2,
        [Description("A+")] Aplus,
        [Description("A")] A,
        [Description("B+")] Bplus,
        [Description("B")] B,
        [Description("C")] C,
        [Description("D")] D,
        [Description("E")] E,
        [Description("F")] F,
        [Description("G")] G
    }
}

